name: pypi-mobans
nick_name: pypi-mobans
copyright_year: 2018
file_type: file type
author: C.W.
organisation: moremoban
contact: wangc_2011@hotmail.com
license: NEW BSD
company: Onni Software Ltd.
branch: master
description: this is a base for python project scaffolding
